export const cuisineList = [
  // General Indian Dishes
  "Biryani",
  "Butter Chicken",
  "Chaat",
  "Chole Bhature",
  "Dal Makhani",
  "Dosa",
  "Gulab Jamun",
  "Hyderabadi",
  "Idli",
  "Kebab",
  "Korma",
  "Mughlai",
  "Pani Puri",
  "Paneer",
  "Paratha",
  "Rogan Josh",
  "Samosa",
  "South Indian",
  "Tandoori",
  "Thali",
  "Vindaloo",
  "Vada Pav",
  "Rasam",
  "Pongal",
  "Uttapam",
  "Lassi",
  
  // South Indian Dishes
  "Appam",
  "Chettinad Chicken",
  "Fish Curry",
  "Masala Dosa",
  "Neer Dosa",
  "Puttu",
  "Sambar",
  "Vada",

  // Andhra Pradesh and Telangana
  "Andhra Chicken Curry",
  "Gongura Mutton",
  "Hyderabadi Biryani",
  "Pesarattu",
  "Pulihora",
  "Kodi Kura",
  "Ariselu",
  "Bobbatlu",

  // Karnataka
  "Bisi Bele Bath",
  "Mysore Masala Dosa",
  "Mangalore Buns",
  "Mysore Pak",
  "Ragi Mudde",
  "Mysore Bonda",
  "Coorgi Pandi Curry",
  "Neer Dosa",

  // Tamil Nadu
  "Chettinad Chicken",
  "Kothu Parotta",
  "Pongal",
  "Rasam",
  "Meen Kuzhambu",
  "Idiyappam",
  "Paruppu Payasam",
  "Kuzhi Paniyaram",

  // Kerala
  "Kerala Fish Curry",
  "Appam",
  "Puttu",
  "Erissery",
  "Beef Fry",
  "Avial",
  "Palada Payasam",
  "Thalassery Biryani",
];
